-- קובץ seed אוטומטי - אל תערוך ידנית!
-- נוצר ע"י seed/generate-seed.mjs (מריצים: node seed/generate-seed.mjs)
-- סיסמאות: admin/warehouse = "password123", סניפים = "Mia{מספר}"

-- ===== סניפים =====
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('WH-CENTRAL', NULL, 'מחסן מרכזי - מייה', 'הרימון 8', 'שוהם', '6082935', NULL, 'מנהל מחסן', '0508754123', 1);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-11', 11, 'מייה איילון', NULL, 'רמת גן', NULL, NULL, NULL, '050-1902011', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-12', 12, 'מייה רחובות', NULL, 'רחובות', NULL, NULL, NULL, '050-1902012', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-13', 13, 'מייה זהב ראשון לציון', NULL, 'ראשון לציון', NULL, NULL, NULL, '050-1902013', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-14', 14, 'מייה גבעתיים', NULL, 'גבעתיים', NULL, NULL, NULL, '050-1902014', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-15', 15, 'מייה גרנד חיפה', NULL, 'חיפה', NULL, NULL, NULL, '050-1902015', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-16', 16, 'מייה קריון', NULL, 'קרית ביאליק', NULL, NULL, NULL, '050-1902016', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-17', 17, 'מייה אבנת פתח תקווה', NULL, 'פתח תקווה', NULL, NULL, NULL, '050-1902017', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-18', 18, 'מייה ביג אשדוד', NULL, 'אשדוד', NULL, NULL, NULL, '050-1902018', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-19', 19, 'מייה עזריאלי תל אביב', NULL, 'תל אביב', NULL, NULL, NULL, '050-1902019', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-20', 20, 'מייה עזריאלי חולון', NULL, 'חולון', NULL, NULL, NULL, '050-1902020', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-21', 21, 'מייה גרנד באר שבע', NULL, 'באר שבע', NULL, NULL, NULL, '050-1902021', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-22', 22, 'מייה עיר ימים נתניה', NULL, 'נתניה', NULL, NULL, NULL, '050-1902022', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-23', 23, 'מייה ביג באר שבע', NULL, 'באר שבע', NULL, NULL, NULL, '050-1902023', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-26', 26, 'מייה רוטשילד ראשון לציון', NULL, 'ראשון לציון', NULL, NULL, NULL, '050-1902026', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-27', 27, 'מייה מלחה ירושלים', NULL, 'ירושלים', NULL, NULL, NULL, '050-1902027', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-28', 28, 'מייה ממילא ירושלים', NULL, 'ירושלים', NULL, NULL, NULL, '050-1902028', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-29', 29, 'מייה ביג גלילות', NULL, 'רמת השרון', NULL, NULL, NULL, '050-1902029', 0);
INSERT INTO branches (code, branch_number, name, address, city, zip, phone, contact_name, contact_phone, is_warehouse) VALUES ('BR-30', 30, 'מייה חוצות המפרץ', NULL, 'חיפה', NULL, NULL, NULL, '050-5172030', 0);

-- ===== משתמשים =====
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('admin', 'pbkdf2$100000$A3qBgr7DvVl5NRCjwYctRQ==$Tvkg+UfWAitzhX0D48B2HPBd3M06sdCLZYrt+JYUR4E=', 'מנהל מערכת', 'admin', NULL);
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('warehouse', 'pbkdf2$100000$G4rXPhLH+NO5hYt8Xpbduw==$54g+NFCCGdZm6MWdV4dCd+HnH5F73Ax5IZg1rg3BnwM=', 'מנהל מחסן מרכזי', 'warehouse', (SELECT id FROM branches WHERE code = 'WH-CENTRAL'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('11', 'pbkdf2$100000$LxF0F2vmaZlOtpPMY/B1Nw==$othnjhT0YtPo3k/d62qo3U2M7Q+LOVWH4eF7vt5lpzk=', 'מנהלת סניף איילון', 'branch', (SELECT id FROM branches WHERE code = 'BR-11'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('12', 'pbkdf2$100000$EWvrVWpvooui+PXjy2suCw==$RoC86t+nCAQm83y44YxtYl5U+5tRbwicOJFX83BKmbI=', 'מנהלת סניף רחובות', 'branch', (SELECT id FROM branches WHERE code = 'BR-12'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('13', 'pbkdf2$100000$yUDpLCWKeDYi071Ib7Oylw==$peNd7uU+a81CYBiuDEirPWKkBg8ShfK8QIJwfGiNq0g=', 'מנהלת סניף זהב ראשון לציון', 'branch', (SELECT id FROM branches WHERE code = 'BR-13'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('14', 'pbkdf2$100000$s93plJmMruooSCQWfIN2Ag==$HZ4TQGgUZ+KW0655pSTlPmWrTZUP4QCWSUoCCGURgiI=', 'מנהלת סניף גבעתיים', 'branch', (SELECT id FROM branches WHERE code = 'BR-14'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('15', 'pbkdf2$100000$biJnZoE4GXicPcEc6pMFmA==$9F9HpUZhUq/gLOaAMASvbvungG9pOaCRv1wHUT5ZES0=', 'מנהלת סניף גרנד חיפה', 'branch', (SELECT id FROM branches WHERE code = 'BR-15'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('16', 'pbkdf2$100000$fbkngi9gOkcqpNY74fS0sA==$ghYmDiA668VCzeAwfosOa4Qti6TTn8eT+O1RwithctI=', 'מנהלת סניף קריון', 'branch', (SELECT id FROM branches WHERE code = 'BR-16'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('17', 'pbkdf2$100000$AcqCUZYDNVjlbIyJ5eOAhg==$A0CLMi9MXpNKZsUU90fzE7SMrlpYNaLkA7ubtuXTO/w=', 'מנהלת סניף אבנת פתח תקווה', 'branch', (SELECT id FROM branches WHERE code = 'BR-17'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('18', 'pbkdf2$100000$Sp0CQpggEcYB3HofffcRvw==$vxZDbrX4t4kciUqhfqDrkhsl3+AeidxPu1O9Oed1xlw=', 'מנהלת סניף ביג אשדוד', 'branch', (SELECT id FROM branches WHERE code = 'BR-18'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('19', 'pbkdf2$100000$ai1jOymTNPFr+1XzDuxTSw==$8pKhPcsmr6v7zLJUk/JKeTK+wrZ3DJ2FApsKe5WTBFE=', 'מנהלת סניף עזריאלי תל אביב', 'branch', (SELECT id FROM branches WHERE code = 'BR-19'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('20', 'pbkdf2$100000$8hsif+zmbwyEQHRoBb45ew==$7SrkHhh0iXlH43iooKjbnsug6g5Fz61tzVM1gnEQtqQ=', 'מנהלת סניף עזריאלי חולון', 'branch', (SELECT id FROM branches WHERE code = 'BR-20'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('21', 'pbkdf2$100000$wJBp9dQZscZLxNGhHaRdqA==$rekFhojpU7YkvF4ksy9m4VYq2/cZVkUNj6neLAqAAGk=', 'מנהלת סניף גרנד באר שבע', 'branch', (SELECT id FROM branches WHERE code = 'BR-21'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('22', 'pbkdf2$100000$6DBtSlLfrrhw9PQShYfWOg==$VLTMVEC5STeJuvi5Ddt6bMCoOKMeqyA1fnu2t8H9SGc=', 'מנהלת סניף עיר ימים נתניה', 'branch', (SELECT id FROM branches WHERE code = 'BR-22'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('23', 'pbkdf2$100000$CCOdPG1oJ6U6ewKQddzXVQ==$OpyZRgm8mNrybrlnrWMBkwGDo42AvwYxShry+tojYTM=', 'מנהלת סניף ביג באר שבע', 'branch', (SELECT id FROM branches WHERE code = 'BR-23'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('26', 'pbkdf2$100000$AoB1L9SwaDITzcA1orALxA==$wPO9nqSWORWx13AJWpg9GEg7bC8JMVVmSJZq6H545h0=', 'מנהלת סניף רוטשילד ראשון לציון', 'branch', (SELECT id FROM branches WHERE code = 'BR-26'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('27', 'pbkdf2$100000$iLApPyPHfyaDCrlvhXiLbA==$0JXVH9d6XV+0DjKWaMm+e/r79NQ1qS4jAHkVrm1DpNs=', 'מנהלת סניף מלחה ירושלים', 'branch', (SELECT id FROM branches WHERE code = 'BR-27'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('28', 'pbkdf2$100000$NGLtsMnjQ5dtp5/z6Dj3CA==$SLdBPResm1lipE3/Z0KDEevvXBfVe61GZSGtq/NAjjI=', 'מנהלת סניף ממילא ירושלים', 'branch', (SELECT id FROM branches WHERE code = 'BR-28'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('29', 'pbkdf2$100000$YRwXQst4YmV82WF9PNLwVQ==$uOjaa5mLN/KY16RZANA9FNNQkd3G2Axkk0NsPVQN5/Q=', 'מנהלת סניף ביג גלילות', 'branch', (SELECT id FROM branches WHERE code = 'BR-29'));
INSERT INTO users (username, password_hash, full_name, role, branch_id) VALUES ('30', 'pbkdf2$100000$lS4gCYvcvTgu9vvR4SHZqQ==$tQfiQ7VhSOwWhEwSfE9nTzQCh38tWJwzLlcScftVxBY=', 'מנהלת סניף חוצות המפרץ', 'branch', (SELECT id FROM branches WHERE code = 'BR-30'));
